---
- name: Converge
  hosts: all
  tasks:
    - name: Common Role
      include_role:
        name: "redhat-cop.jboss_common"
    - name: Red Hat SSO Role
      include_role:
        name: "../../../"
